version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(levelname)s %(asctime)s: %(message)s"
  detailed:
    format: "%(levelname)s %(name)s [%(asctime)s] (line %(lineno)d filename %(filename)s): %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
handlers:
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: "$LOGDIR/helpex.log"
    backupCount: 3
    maxBytes: 10240
loggers:
  root:
    level: DEBUG
    handlers:
      - stderr
      - file
